export const LOADING_NEWS = 'LOADING_NEWS';

export const CHANGED_CATEGORY = 'CHANGED_CATEGORY';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';

export const REQUEST_NEWS_SOURCES = 'REQUEST_NEWS_SOURCES';
export const REQUEST_NEWS_SOURCES_ERROR = 'REQUEST_NEWS_SOURCES_ERROR';
export const RECEIVED_NEWS_SOURCES = 'RECEIVED_NEWS_SOURCES';
export const CHANGED_NEWS_SOURCE = 'CHANGED_NEWS_SOURCE';
export const SELECTED_NEWS_SOURCE = 'SELECTED_NEWS_SOURCE';

export const SELECTED_NEWS = 'SELECTED_NEWS';
